name: Do Commit Push and Jekyll

on:
  schedule:
#     - cron: "0 0 1,11,21 * *"
    - cron: "*/20 * * * *"


jobs:
  consecutiveness:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        bash get-data-origin.sh
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: get new data & update
        
  build:
    runs-on: ubuntu-latest
    needs: [ consecutiveness ]
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Jekyll Actions
        # You may pin to the exact commit or the version.
        # uses: https://github.com/helaili/jekyll-action
        uses: helaili/jekyll-action@2.3.1
        with:
          # The GITHUB_TOKEN secret
          token: ${{ secrets.GITHUB_TOKEN }}
          # The target branch name the site gets pushed to
          target_branch: gh-pages
          # pre_build_commands: "bash get-data-origin.sh"
