name: Get Commit and Push

on:
  schedule:
    - cron: "0 0 1,11,21 * *"
#     - cron: "*/20 * * * *"
  workflow_dispatch:
    inputs:
      tags:
        description: 'Activate Manually'
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    # https://github.com/ruby/setup-ruby
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle install
    - name: Create local changes
      run: |
        bash run_all.sh
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: get new data & update
